(() => {
'use strict';
const cfg=window.SUMEE_SUPABASE;
const db=window.supabase.createClient(cfg.url,cfg.publishableKey);
const $=s=>document.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const fmt=d=>d?new Date(d).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const localInput=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,16)};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const state={items:[],customers:[],orders:[],partners:[]};
const modal=$('#modal'), mc=$('#modalContent');
function toast(msg,error=false){const el=$('#appMessage');el.textContent=msg;el.hidden=false;el.style.background=error?'#fdeaea':'#fff4d6';clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,4500)}
function showModal(title,html){mc.innerHTML=`<h2>${esc(title)}</h2>${html}`;modal.showModal()}
$('.modal-close').onclick=()=>modal.close();
function go(page){$$('.page').forEach(x=>x.classList.remove('active'));$$('.navtab').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#'+page)?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(page==='dashboard')loadDashboard();if(page==='customers')loadCustomers();if(page==='items')loadItems();if(page==='receivable')loadReceivables();if(page==='partners')loadPartners();if(page==='neworder')prepareNewOrder();}
$$('.navtab').forEach(b=>b.onclick=()=>go(b.dataset.page));document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)go(b.dataset.go)});

async function requireAdmin(){
 const {data:{session}}=await db.auth.getSession();
 if(!session)return false;
 const {data,error}=await db.from('admin_users').select('user_id,email,active').eq('user_id',session.user.id).maybeSingle();
 if(error||!data?.active){await db.auth.signOut();return false}
 $('#adminEmail').textContent=session.user.email;return true;
}
async function boot(){const ok=await requireAdmin();$('#loginScreen').hidden=ok;$('#adminApp').hidden=!ok;if(ok){setDefaults();await Promise.all([loadItems(),loadCustomers()]);await loadDashboard();}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMessage').textContent='Signing in…';const {error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error){$('#loginMessage').textContent=error.message;return}if(!await requireAdmin()){$('#loginMessage').textContent='This account is not authorized as a SuMee admin.';return}$('#loginScreen').hidden=true;$('#adminApp').hidden=false;$('#loginMessage').textContent='';setDefaults();await Promise.all([loadItems(),loadCustomers(),loadDashboard()]);};
$('#signOut').onclick=async()=>{await db.auth.signOut();location.reload()};

function setDefaults(){const now=new Date(), event=new Date(now);event.setDate(event.getDate()+7);event.setHours(17,0,0,0);const delivery=new Date(event);delivery.setHours(13);const pickup=new Date(event);pickup.setDate(pickup.getDate()+1);pickup.setHours(10);$('#orderEvent').value=localInput(event);$('#orderDelivery').value=localInput(delivery);$('#orderPickup').value=localInput(pickup);$('#availabilityFrom').value=localInput(delivery);$('#availabilityPickup').value=localInput(pickup);updateRelease();}
function updateRelease(){if(!$('#orderPickup').value)return;const d=new Date($('#orderPickup').value);d.setHours(d.getHours()+2);$('#releaseTime').textContent=fmt(d)}
$('#orderPickup').addEventListener('change',updateRelease);

async function loadDashboard(){
 const [{data:k,error:ke},{data:o,error:oe}]=await Promise.all([db.from('vw_dashboard_kpis').select('*').single(),db.from('vw_order_financials').select('*').neq('order_status','Cancelled').order('event_date_time')]);
 if(ke||oe){toast((ke||oe).message,true);return}
 $('#ytdRevenue').textContent=money(k.ytd_collected_revenue);$('#outstandingBalance').textContent=money(k.outstanding_balance);state.orders=o||[];
 const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+8);
 const deliveries=o.filter(x=>x.delivery_request_date_time&&new Date(x.delivery_request_date_time)>=start&&new Date(x.delivery_request_date_time)<end&&x.delivery_status!=='Delivered');
 const pickups=o.filter(x=>x.pickup_request_date_time&&new Date(x.pickup_request_date_time)>=start&&new Date(x.pickup_request_date_time)<end&&x.pickup_status!=='Picked Up');
 const ids=new Set([...deliveries,...pickups].map(x=>x.order_id));
 const future=o.filter(x=>new Date(x.event_date_time)>new Date()&&!ids.has(x.order_id)&&!(x.pickup_status==='Picked Up'&&x.final_status==='Settled'));
 renderDispatch('#upcomingDeliveries',deliveries,'delivery_request_date_time','delivery');renderDispatch('#upcomingPickups',pickups,'pickup_request_date_time','pickup');
 $('#futureEventsTable tbody').innerHTML=future.length?future.map(x=>`<tr><td><button class="text-btn order-open" data-id="${x.order_id}">${esc(x.order_number)}</button></td><td>${esc(x.customer_name)}</td><td>${fmt(x.event_date_time)}</td><td>${fmt(x.delivery_request_date_time)}</td><td>${fmt(x.pickup_request_date_time)}</td><td>${money(x.amount_pending)}</td><td>${esc(x.order_status)}</td></tr>`).join(''):`<tr><td colspan="7" class="empty-state">No additional future events.</td></tr>`;applyLabels();
}
function renderDispatch(sel,rows,dateField,type){$(sel).innerHTML=rows.length?`<div class="dispatch-list">${rows.map(x=>`<div class="dispatch-row"><div><button class="text-btn order-open" data-id="${x.order_id}"><strong>${esc(x.order_number)}</strong></button> — ${esc(x.customer_name)}<small>${fmt(x[dateField])}</small></div><button class="secondary fulfill" data-id="${x.order_id}" data-type="${type}">${type==='delivery'?'Mark Delivered':'Mark Picked Up'}</button></div>`).join('')}</div>`:`<div class="empty-state">Nothing scheduled.</div>`}

async function loadCustomers(){const {data,error}=await db.from('vw_customer_lifetime_value').select('*').order('customer_name');if(error){toast(error.message,true);return}state.customers=data||[];renderCustomers();fillCustomerSelect();}
function renderCustomers(){const q=$('#customerSearch').value.toLowerCase();const rows=state.customers.filter(c=>`${c.customer_name} ${c.phone} ${c.email} ${c.city}`.toLowerCase().includes(q));$('#customerTable tbody').innerHTML=rows.length?rows.map(c=>`<tr><td>${esc(c.customer_name)}</td><td>${esc(c.phone)}</td><td><strong>${money(c.lifetime_value)}</strong></td><td class="customer-actions"><button class="text-btn customer-edit" data-id="${c.customer_id}">View/Edit Customer</button><button class="text-btn customer-new-order" data-id="${c.customer_id}">New Order</button><button class="text-btn customer-orders" data-id="${c.customer_id}">View/Edit Orders</button><button class="text-btn customer-payments" data-id="${c.customer_id}">Add/Edit Payments</button></td></tr>`).join(''):`<tr><td colspan="4" class="empty-state">No customers found.</td></tr>`;applyLabels()}
$('#customerSearch').oninput=renderCustomers;
function fillCustomerSelect(selected){$('#orderCustomer').innerHTML=state.customers.map(c=>`<option value="${c.customer_id}" ${String(c.customer_id)===String(selected)?'selected':''}>${esc(c.customer_name)} — ${esc(c.phone)}</option>`).join('')}
$('#addCustomer').onclick=()=>customerEditor();
function customerEditor(c={}){showModal(c.customer_id?'Edit Customer':'Add Customer',`<form id="customerForm" class="modal-grid"><label>Name<input name="customer_name" required value="${esc(c.customer_name)}"></label><label>Phone<input name="phone" required value="${esc(c.phone)}"></label><label>Email<input name="email" type="email" value="${esc(c.email)}"></label><label>City<input name="city" value="${esc(c.city)}"></label><label class="wide">Address<input name="address" value="${esc(c.address)}"></label><label>State<input name="state" value="${esc(c.state||'TX')}"></label><label>ZIP<input name="zip_code" value="${esc(c.zip_code)}"></label><div class="modal-actions wide"><button class="primary" type="submit">Save Customer</button></div></form>`);$('#customerForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));const q=c.customer_id?db.from('customers').update(v).eq('customer_id',c.customer_id):db.from('customers').insert(v);const {error}=await q;if(error)return toast(error.message,true);modal.close();toast('Customer saved.');await loadCustomers();}}

async function loadItems(){const {data,error}=await db.from('items').select('*').order('item_name');if(error){toast(error.message,true);return}state.items=data||[];$('#itemsBody').innerHTML=state.items.length?state.items.map(i=>`<tr><td>${esc(i.item_name)}</td><td>${esc(i.description)}</td><td>${i.qty_on_hand}</td><td>${money(i.unit_price)}</td><td><span class="status-pill ${i.active?'yes':'no'}">${i.active?'Yes':'No'}</span></td><td><button class="text-btn item-edit" data-id="${i.item_id}">Edit</button></td></tr>`).join(''):`<tr><td colspan="6" class="empty-state">No items.</td></tr>`;applyLabels()}
$('#newItem').onclick=()=>itemEditor();
function itemEditor(i={}){showModal(i.item_id?'Edit Item':'Add Item',`<form id="itemForm" class="modal-grid"><label>Item Name<input name="item_name" required value="${esc(i.item_name)}"></label><label>Total Qty<input name="qty_on_hand" type="number" min="0" required value="${i.qty_on_hand??0}"></label><label class="wide">Description<input name="description" value="${esc(i.description)}"></label><label>Unit Price<input name="unit_price" type="number" min="0" step=".01" required value="${i.unit_price??0}"></label><label>Active<select name="active"><option value="true" ${i.active!==false?'selected':''}>Yes</option><option value="false" ${i.active===false?'selected':''}>No</option></select></label><div class="modal-actions wide"><button class="primary" type="submit">Save Item</button></div></form>`);$('#itemForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.qty_on_hand=+v.qty_on_hand;v.unit_price=+v.unit_price;v.active=v.active==='true';const q=i.item_id?db.from('items').update(v).eq('item_id',i.item_id):db.from('items').insert(v);const {error}=await q;if(error)return toast(error.message,true);modal.close();toast('Item saved.');await loadItems();}}

async function checkAvailability(){const from=$('#availabilityFrom').value,pickup=$('#availabilityPickup').value;if(!from||!pickup)return toast('Choose both dates.',true);const {data,error}=await db.rpc('check_inventory_availability',{p_delivery_date_time:new Date(from).toISOString(),p_pickup_date_time:new Date(pickup).toISOString()});if(error)return toast(error.message,true);$('#availabilityBody').innerHTML=data.map(i=>`<tr><td>${esc(i.item_name)}</td><td>${i.qty_on_hand}</td><td>${i.qty_reserved}</td><td><strong class="${i.qty_available<=0?'danger':''}">${i.qty_available}</strong></td></tr>`).join('');applyLabels()}
$('#checkAvailability').onclick=checkAvailability;

function prepareNewOrder(customerId){fillCustomerSelect(customerId);$('#orderItems tbody').innerHTML='';addOrderLine();recalcOrder();}
function addOrderLine(){const active=state.items.filter(i=>i.active);if(!active.length)return;const i=active[0];$('#orderItems tbody').insertAdjacentHTML('beforeend',`<tr><td><select class="oi-item">${active.map(x=>`<option value="${x.item_id}">${esc(x.item_name)}</option>`).join('')}</select></td><td class="oi-avail">${i.qty_on_hand}</td><td><input class="oi-qty" type="number" min="1" value="1"></td><td><input class="oi-price" type="number" min="0" step=".01" value="${i.unit_price}"></td><td class="oi-amount">${money(i.unit_price)}</td><td><button type="button" class="text-btn oi-remove">Remove</button></td></tr>`);recalcOrder();applyLabels()}
$('#addItem').onclick=addOrderLine;
function recalcOrder(){let s=0;$$('#orderItems tbody tr').forEach(r=>{const q=+r.querySelector('.oi-qty').value||0,p=+r.querySelector('.oi-price').value||0;s+=q*p;r.querySelector('.oi-amount').textContent=money(q*p)});const total=s+(+$('#setup').value||0)+(+$('#deliveryFee').value||0)-(+$('#discount').value||0);$('#suggested').textContent=money(s);$('#total').textContent=money(total)}
document.addEventListener('input',e=>{if(e.target.matches('.oi-qty,.oi-price,#setup,#deliveryFee,#discount'))recalcOrder()});
document.addEventListener('change',e=>{if(e.target.matches('.oi-item')){const r=e.target.closest('tr'),i=state.items.find(x=>String(x.item_id)===e.target.value);r.querySelector('.oi-avail').textContent=i.qty_on_hand;r.querySelector('.oi-price').value=i.unit_price;recalcOrder()}});
document.addEventListener('click',e=>{if(e.target.closest('.oi-remove')){e.target.closest('tr').remove();recalcOrder()}});
async function saveOrder(status){const rows=$$('#orderItems tbody tr');if(!rows.length)return toast('Add at least one rental item.',true);const order={customer_id:+$('#orderCustomer').value,event_date_time:new Date($('#orderEvent').value).toISOString(),event_address:$('#orderAddress').value.trim()||null,event_city:$('#orderCity').value.trim()||null,delivery_request_date_time:new Date($('#orderDelivery').value).toISOString(),pickup_request_date_time:new Date($('#orderPickup').value).toISOString(),setup_fee:+$('#setup').value||0,delivery_fee:+$('#deliveryFee').value||0,discount_amount:+$('#discount').value||0,order_status:status,notes:$('#orderNotes').value.trim()||null};const {data:o,error}=await db.from('orders').insert(order).select('order_id,order_number').single();if(error)return toast(error.message,true);const lines=rows.map(r=>({order_id:o.order_id,item_id:+r.querySelector('.oi-item').value,quantity:+r.querySelector('.oi-qty').value,unit_price:+r.querySelector('.oi-price').value}));const {error:ie}=await db.from('order_items').insert(lines);if(ie)return toast(`Order ${o.order_number} was created, but items failed: ${ie.message}`,true);toast(`${o.order_number} saved as ${status}.`);resetOrderForm();await Promise.all([loadDashboard(),loadReceivables()]);go('dashboard')}
function resetOrderForm(){$('#orderAddress').value='';$('#orderCity').value='';$('#setup').value=0;$('#deliveryFee').value=0;$('#discount').value=0;$('#orderNotes').value='';setDefaults();prepareNewOrder()}
$('#saveDraft').onclick=()=>saveOrder('Draft');$('#confirmOrder').onclick=()=>saveOrder('Confirmed');

async function loadReceivables(){const {data,error}=await db.from('vw_receivables').select('*').order('event_date_time',{ascending:false});if(error){toast(error.message,true);return}state.receivables=data||[];renderReceivables()}
function renderReceivables(){const q=$('#receivableSearch').value.toLowerCase();const r=state.receivables.filter(x=>`${x.customer_name} ${x.phone} ${x.email} ${x.city}`.toLowerCase().includes(q));$('#receivableTable tbody').innerHTML=r.length?r.map(x=>`<tr><td>${fmt(x.event_date_time)}</td><td>${fmt(x.pickup_request_date_time)}</td><td><button class="text-btn order-open" data-id="${x.order_id}">${esc(x.order_number)}</button></td><td>${esc(x.customer_name)}</td><td>${esc(x.phone)}</td><td>${money(x.order_total)}</td><td>${money(x.amount_paid)}</td><td><strong class="danger">${money(x.amount_pending)}</strong></td></tr>`).join(''):`<tr><td colspan="8" class="empty-state">No outstanding receivables.</td></tr>`;applyLabels()}
$('#receivableSearch').oninput=renderReceivables;$('#addPayment').onclick=()=>paymentEditor();
async function paymentEditor(customerId,orderId){let q=db.from('vw_order_financials').select('order_id,order_number,customer_id,customer_name,amount_pending').neq('order_status','Cancelled').order('event_date_time',{ascending:false});if(customerId)q=q.eq('customer_id',customerId);const {data,error}=await q;if(error)return toast(error.message,true);showModal('Add Payment',`<form id="paymentForm" class="modal-grid"><label>Order<select name="order_id">${data.map(o=>`<option value="${o.order_id}" ${String(o.order_id)===String(orderId)?'selected':''}>${esc(o.order_number)} — ${esc(o.customer_name)} — ${money(o.amount_pending)} due</option>`).join('')}</select></label><label>Type<select name="transaction_type"><option>Payment</option><option>Refund</option></select></label><label>Date / Time<input name="payment_date_time" type="datetime-local" value="${localInput(new Date())}"></label><label>Amount<input name="amount" type="number" min=".01" step=".01" required></label><label>Method<select name="payment_method"><option>Zelle</option><option>Cash</option><option>Venmo</option><option>Credit Card</option><option>Check</option><option>Other</option></select></label><label>Reference<input name="reference_number"></label><label class="wide">Notes<input name="notes"></label><div class="modal-actions wide"><button class="primary" type="submit">Save Payment</button></div></form>`);$('#paymentForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.order_id=+v.order_id;v.amount=+v.amount;v.payment_date_time=new Date(v.payment_date_time).toISOString();const {error}=await db.from('payments').insert(v);if(error)return toast(error.message,true);modal.close();toast('Payment saved.');await Promise.all([loadReceivables(),loadDashboard(),loadCustomers()]);}}

async function openOrder(orderId){const [{data:o,error},{data:lines},{data:pays}]=await Promise.all([db.from('vw_order_financials').select('*').eq('order_id',orderId).single(),db.from('order_items').select('order_item_id,item_id,quantity,unit_price,items(item_name)').eq('order_id',orderId),db.from('payments').select('*').eq('order_id',orderId).order('payment_date_time',{ascending:false})]);if(error)return toast(error.message,true);showModal(`Order ${o.order_number}`,`<div class="order-detail-head"><div><p><strong>${esc(o.customer_name)}</strong> · ${esc(o.order_status)} · ${esc(o.final_status)}</p></div><div class="order-detail-actions"><button class="secondary" onclick="window.print()">Print / Save PDF</button></div></div><div class="order-meta"><div><span>Phone</span><strong>${esc(o.phone)}</strong></div><div><span>Email</span><strong>${esc(o.email)}</strong></div><div><span>Event</span><strong>${fmt(o.event_date_time)}</strong></div><div><span>Delivery</span><strong>${fmt(o.delivery_request_date_time)}</strong></div><div><span>Pickup</span><strong>${fmt(o.pickup_request_date_time)}</strong></div><div><span>Balance</span><strong>${money(o.amount_pending)}</strong></div></div><h3>Packing List</h3><div class="table-wrap"><table><thead><tr><th>Item</th><th>Qty</th><th>Unit Price</th><th>Amount</th></tr></thead><tbody>${lines.map(x=>`<tr><td>${esc(x.items?.item_name)}</td><td><strong>${x.quantity}</strong></td><td>${money(x.unit_price)}</td><td>${money(x.quantity*x.unit_price)}</td></tr>`).join('')}</tbody></table></div><div class="order-summary"><div><span>Suggested Price</span><strong>${money(o.suggested_price)}</strong></div><div><span>Setup Fee</span><strong>${money(o.setup_fee)}</strong></div><div><span>Delivery Fee</span><strong>${money(o.delivery_fee)}</strong></div><div><span>Discount</span><strong>−${money(o.discount_amount)}</strong></div><div class="grand-total"><span>Total</span><strong>${money(o.total_amount)}</strong></div><div><span>Received</span><strong>${money(o.amount_received)}</strong></div><div><span>Pending</span><strong>${money(o.amount_pending)}</strong></div></div><h3>Payments</h3>${pays.length?pays.map(p=>`<p>${fmt(p.payment_date_time)} — ${esc(p.transaction_type)} ${money(p.amount)} (${esc(p.payment_method||'')})</p>`).join(''):'<p>No payments yet.</p>'}<div class="modal-actions"><button class="secondary order-add-payment" data-id="${o.order_id}" data-customer="${o.customer_id}">Add Payment</button></div>`);applyLabels(mc)}

async function loadPartners(){const {data,error}=await db.from('partners').select('*').order('display_order').order('business_name');if(error){toast(error.message,true);return}state.partners=data||[];renderPartners()}
function renderPartners(){const q=$('#partnerSearch').value.toLowerCase();const r=state.partners.filter(p=>`${p.business_name} ${p.category} ${p.contact_name} ${p.service_areas}`.toLowerCase().includes(q));$('#partnersTable tbody').innerHTML=r.length?r.map(p=>`<tr><td>${esc(p.business_name)}</td><td>${esc(p.category)}</td><td>${esc(p.phone)}</td><td>${p.featured?'Yes':'No'}</td><td>${p.active?'Yes':'No'}</td><td>${p.display_order}</td><td class="partner-actions"><button class="text-btn partner-edit" data-id="${p.partner_id}">Edit</button></td></tr>`).join(''):`<tr><td colspan="7" class="empty-state">No partners yet.</td></tr>`;applyLabels()}
$('#partnerSearch').oninput=renderPartners;$('#newPartner').onclick=()=>partnerEditor();
function partnerEditor(p={}){showModal(p.partner_id?'Edit Partner':'Add Partner',`<form id="partnerForm" class="modal-grid"><label>Business Name<input name="business_name" required value="${esc(p.business_name)}"></label><label>Category<input name="category" required placeholder="Photographer, Decorator, Henna Artist..." value="${esc(p.category)}"></label><label>Contact Name<input name="contact_name" value="${esc(p.contact_name)}"></label><label>Phone<input name="phone" value="${esc(p.phone)}"></label><label>Email<input name="email" type="email" value="${esc(p.email)}"></label><label>Website<input name="website_url" value="${esc(p.website_url)}"></label><label>Instagram<input name="instagram_url" value="${esc(p.instagram_url)}"></label><label>Facebook<input name="facebook_url" value="${esc(p.facebook_url)}"></label><label class="wide">Service Areas<input name="service_areas" value="${esc(p.service_areas)}"></label><label class="wide">Description<textarea name="description">${esc(p.description)}</textarea></label><label class="wide">Image URL<input name="image_url" value="${esc(p.image_url)}"></label><label>Featured<select name="featured"><option value="false" ${!p.featured?'selected':''}>No</option><option value="true" ${p.featured?'selected':''}>Yes</option></select></label><label>Active<select name="active"><option value="true" ${p.active!==false?'selected':''}>Yes</option><option value="false" ${p.active===false?'selected':''}>No</option></select></label><label>Display Order<input name="display_order" type="number" min="0" value="${p.display_order??0}"></label><div class="modal-actions wide"><button class="primary" type="submit">Save Partner</button></div></form>`);$('#partnerForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.featured=v.featured==='true';v.active=v.active==='true';v.display_order=+v.display_order||0;const q=p.partner_id?db.from('partners').update(v).eq('partner_id',p.partner_id):db.from('partners').insert(v);const {error}=await q;if(error)return toast(error.message,true);modal.close();toast('Partner saved.');await loadPartners();}}

document.addEventListener('click',async e=>{
 const ce=e.target.closest('.customer-edit');if(ce)return customerEditor(state.customers.find(c=>String(c.customer_id)===ce.dataset.id));
 const cn=e.target.closest('.customer-new-order');if(cn){go('neworder');prepareNewOrder(cn.dataset.id);return}
 const co=e.target.closest('.customer-orders');if(co){const {data,error}=await db.from('vw_order_financials').select('*').eq('customer_id',co.dataset.id).order('event_date_time',{ascending:false});if(error)return toast(error.message,true);showModal('Customer Orders',data.length?`<div class="table-wrap"><table><thead><tr><th>Event</th><th>Order</th><th>Total</th><th>Balance</th></tr></thead><tbody>${data.map(o=>`<tr><td>${fmt(o.event_date_time)}</td><td><button class="text-btn order-open" data-id="${o.order_id}">${esc(o.order_number)}</button></td><td>${money(o.total_amount)}</td><td>${money(o.amount_pending)}</td></tr>`).join('')}</tbody></table></div>`:'<p>No orders.</p>');applyLabels(mc);return}
 const cp=e.target.closest('.customer-payments');if(cp)return paymentEditor(cp.dataset.id);
 const ie=e.target.closest('.item-edit');if(ie)return itemEditor(state.items.find(i=>String(i.item_id)===ie.dataset.id));
 const pe=e.target.closest('.partner-edit');if(pe)return partnerEditor(state.partners.find(p=>String(p.partner_id)===pe.dataset.id));
 const oo=e.target.closest('.order-open');if(oo)return openOrder(+oo.dataset.id);
 const op=e.target.closest('.order-add-payment');if(op){modal.close();return paymentEditor(op.dataset.customer,op.dataset.id)}
 const f=e.target.closest('.fulfill');if(f){const now=new Date().toISOString(),update=f.dataset.type==='delivery'?{delivery_status:'Delivered',actual_delivery_date_time:now}:{pickup_status:'Picked Up',actual_pickup_date_time:now};const {error}=await db.from('orders').update(update).eq('order_id',f.dataset.id);if(error)return toast(error.message,true);toast(f.dataset.type==='delivery'?'Order marked delivered.':'Order marked picked up.');return loadDashboard()}
});

function applyLabels(root=document){root.querySelectorAll('table').forEach(t=>{const h=$$('thead th',t);t.querySelectorAll('tbody tr').forEach(r=>[...r.children].forEach((c,i)=>{if(c.tagName==='TD')c.dataset.label=h[i]?.textContent.trim()||''}))})}
boot();
})();
