(() => {
'use strict';
const cfg=window.SUMEE_SUPABASE;
const db=window.supabase.createClient(cfg.url,cfg.publishableKey);
const $=s=>document.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const fmt=d=>d?new Date(d).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const fmtDate=d=>d?new Date(d+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'—';
const localInput=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,16)};
const dateInput=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const state={items:[],customers:[],orders:[],partners:[],categories:[],receivables:[],availability:[]};
const modal=$('#modal'), mc=$('#modalContent');
function toast(msg,error=false){const el=$('#appMessage');el.textContent=msg;el.hidden=false;el.style.background=error?'#fdeaea':'#fff4d6';clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,5000)}
function showModal(title,html,wide=false){modal.classList.toggle('modal-wide',!!wide);mc.innerHTML=`<h2>${esc(title)}</h2>${html}`;modal.showModal()}
$('.modal-close').onclick=()=>modal.close();
function go(page){$$('.page').forEach(x=>x.classList.remove('active'));$$('.navtab').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#'+page)?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});({dashboard:loadDashboard,customers:loadCustomers,items:loadItems,receivable:loadReceivables,partners:loadPartners,accounting:loadAccounting,neworder:prepareNewOrder}[page]||(()=>{}))()}
$$('.navtab').forEach(b=>b.onclick=()=>go(b.dataset.page));document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)go(b.dataset.go)});

async function requireAdmin(){const {data:{session}}=await db.auth.getSession();if(!session)return false;const {data,error}=await db.from('admin_users').select('user_id,email,active').eq('user_id',session.user.id).maybeSingle();if(error||!data?.active){await db.auth.signOut();return false}$('#adminEmail').textContent=session.user.email;return true}
async function boot(){const ok=await requireAdmin();$('#loginScreen').hidden=ok;$('#adminApp').hidden=!ok;if(ok){setDefaults();await Promise.all([loadItems(),loadCustomers(),loadCategories()]);await loadDashboard()}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMessage').textContent='Signing in…';const {error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error){$('#loginMessage').textContent=error.message;return}if(!await requireAdmin()){$('#loginMessage').textContent='This account is not authorized as a SuMee admin.';return}$('#loginScreen').hidden=true;$('#adminApp').hidden=false;$('#loginMessage').textContent='';setDefaults();await Promise.all([loadItems(),loadCustomers(),loadCategories(),loadDashboard()])};
$('#signOut').onclick=async()=>{await db.auth.signOut();location.reload()};

function setDefaults(){const now=new Date(),event=new Date(now);event.setDate(event.getDate()+7);event.setHours(17,0,0,0);const delivery=new Date(event);delivery.setHours(13);const pickup=new Date(event);pickup.setDate(pickup.getDate()+1);pickup.setHours(10);$('#orderEvent').value=localInput(event);$('#orderDelivery').value=localInput(delivery);$('#orderPickup').value=localInput(pickup);$('#availabilityFrom').value=localInput(delivery);$('#availabilityPickup').value=localInput(pickup);const y=new Date(now.getFullYear(),0,1);$('#accountingFrom').value=dateInput(y);$('#accountingTo').value=dateInput(now);updateRelease()}
function updateRelease(){if(!$('#orderPickup').value)return;const d=new Date($('#orderPickup').value);d.setHours(d.getHours()+2);$('#releaseTime').textContent=fmt(d)}
$('#orderPickup').addEventListener('change',updateRelease);

async function loadDashboard(){const {data:o,error}=await db.from('vw_order_financials').select('*').neq('order_status','Cancelled').order('event_date_time');if(error)return toast(error.message,true);state.orders=o||[];const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+8);const deliveries=state.orders.filter(x=>x.delivery_request_date_time&&new Date(x.delivery_request_date_time)>=start&&new Date(x.delivery_request_date_time)<end&&x.delivery_status!=='Delivered');const pickups=state.orders.filter(x=>x.pickup_request_date_time&&new Date(x.pickup_request_date_time)>=start&&new Date(x.pickup_request_date_time)<end&&x.pickup_status!=='Picked Up');const ids=new Set([...deliveries,...pickups].map(x=>x.order_id));const future=state.orders.filter(x=>new Date(x.event_date_time)>new Date()&&!ids.has(x.order_id)&&!(x.pickup_status==='Picked Up'&&x.final_status==='Settled'));renderDispatch('#upcomingDeliveries',deliveries,'delivery_request_date_time','delivery');renderDispatch('#upcomingPickups',pickups,'pickup_request_date_time','pickup');$('#futureEventsTable tbody').innerHTML=future.length?future.map(x=>`<tr><td><button class="text-btn order-open" data-id="${x.order_id}">${esc(x.order_number)}</button></td><td>${esc(x.customer_name)}</td><td>${fmt(x.event_date_time)}</td><td>${fmt(x.delivery_request_date_time)}</td><td>${fmt(x.pickup_request_date_time)}</td><td>${money(x.amount_pending)}</td><td>${esc(x.order_status)}</td></tr>`).join(''):`<tr><td colspan="7" class="empty-state">No additional future events.</td></tr>`;applyLabels()}
function renderDispatch(sel,rows,dateField,type){$(sel).innerHTML=rows.length?`<div class="dispatch-list">${rows.map(x=>`<div class="dispatch-row"><div><button class="text-btn order-open" data-id="${x.order_id}"><strong>${esc(x.order_number)}</strong></button> — ${esc(x.customer_name)}<small>${fmt(x[dateField])}</small></div><button class="secondary fulfill" data-id="${x.order_id}" data-type="${type}">${type==='delivery'?'Mark Delivered':'Mark Picked Up'}</button></div>`).join('')}</div>`:`<div class="empty-state">Nothing scheduled.</div>`}

async function loadCustomers(){const {data,error}=await db.from('vw_customer_lifetime_value').select('*').order('customer_name');if(error)return toast(error.message,true);state.customers=data||[];renderCustomers();fillCustomerSelect()}
function renderCustomers(){const q=$('#customerSearch').value.toLowerCase();const rows=state.customers.filter(c=>`${c.customer_name} ${c.phone} ${c.email} ${c.city}`.toLowerCase().includes(q));$('#customerTable tbody').innerHTML=rows.length?rows.map(c=>`<tr><td>${esc(c.customer_name)}</td><td>${esc(c.phone)}</td><td><strong>${money(c.lifetime_value)}</strong></td><td class="customer-actions"><button class="text-btn customer-edit" data-id="${c.customer_id}">View/Edit Customer</button><button class="text-btn customer-new-order" data-id="${c.customer_id}">New Order</button><button class="text-btn customer-orders" data-id="${c.customer_id}">View/Edit Orders</button><button class="text-btn customer-payments" data-id="${c.customer_id}">Add/Edit Payments</button></td></tr>`).join(''):`<tr><td colspan="4" class="empty-state">No customers found.</td></tr>`;applyLabels()}
$('#customerSearch').oninput=renderCustomers;
function fillCustomerSelect(selected){$('#orderCustomer').innerHTML=state.customers.map(c=>`<option value="${c.customer_id}" ${String(c.customer_id)===String(selected)?'selected':''}>${esc(c.customer_name)} — ${esc(c.phone)}</option>`).join('')}
$('#addCustomer').onclick=()=>customerEditor();
function customerEditor(c={}){showModal(c.customer_id?'Edit Customer':'Add Customer',`<form id="customerForm" class="modal-grid"><label>Name<input name="customer_name" required value="${esc(c.customer_name)}"></label><label>Phone<input name="phone" required value="${esc(c.phone)}"></label><label>Email<input name="email" type="email" value="${esc(c.email)}"></label><label>City<input name="city" value="${esc(c.city)}"></label><label class="wide">Address<input name="address" value="${esc(c.address)}"></label><label>State<input name="state" value="${esc(c.state||'TX')}"></label><label>ZIP<input name="zip_code" value="${esc(c.zip_code)}"></label><div class="modal-actions wide"><button class="primary" type="submit">Save Customer</button></div></form>`);$('#customerForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));const q=c.customer_id?db.from('customers').update(v).eq('customer_id',c.customer_id):db.from('customers').insert(v);const {error}=await q;if(error)return toast(error.message,true);modal.close();toast('Customer saved.');await loadCustomers()}}

async function loadItems(){const {data,error}=await db.from('items').select('*').order('item_name');if(error)return toast(error.message,true);state.items=data||[];$('#itemsBody').innerHTML=state.items.length?state.items.map(i=>`<tr><td>${esc(i.item_name)}</td><td>${esc(i.description)}</td><td>${i.qty_on_hand}</td><td>${money(i.unit_price)}</td><td><span class="status-pill ${i.active?'yes':'no'}">${i.active?'Yes':'No'}</span></td><td><button class="text-btn item-edit" data-id="${i.item_id}">Edit</button></td></tr>`).join(''):`<tr><td colspan="6" class="empty-state">No items.</td></tr>`;applyLabels()}
$('#newItem').onclick=()=>itemEditor();
function itemEditor(i={}){showModal(i.item_id?'Edit Item':'Add Item',`<form id="itemForm" class="modal-grid"><label>Item Name<input name="item_name" required value="${esc(i.item_name)}"></label><label>Total Qty<input name="qty_on_hand" type="number" min="0" required value="${i.qty_on_hand??0}"></label><label class="wide">Description<input name="description" value="${esc(i.description)}"></label><label>Unit Price<input name="unit_price" type="number" min="0" step=".01" required value="${i.unit_price??0}"></label><label>Active<select name="active"><option value="true" ${i.active!==false?'selected':''}>Yes</option><option value="false" ${i.active===false?'selected':''}>No</option></select></label><div class="modal-actions wide"><button class="primary" type="submit">Save Item</button></div></form>`);$('#itemForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.qty_on_hand=+v.qty_on_hand;v.unit_price=+v.unit_price;v.active=v.active==='true';const q=i.item_id?db.from('items').update(v).eq('item_id',i.item_id):db.from('items').insert(v);const {error}=await q;if(error)return toast(error.message,true);modal.close();toast('Item saved.');await loadItems()}}

async function checkAvailability(from,pickup,exclude=null){if(!from||!pickup)return [];const args={p_delivery_date_time:new Date(from).toISOString(),p_pickup_date_time:new Date(pickup).toISOString(),p_exclude_order_id:exclude};const {data,error}=await db.rpc('check_inventory_availability',args);if(error){toast(error.message,true);return []}return data||[]}
$('#checkAvailability').onclick=async()=>{const rows=await checkAvailability($('#availabilityFrom').value,$('#availabilityPickup').value);$('#availabilityBody').innerHTML=rows.map(i=>`<tr><td>${esc(i.item_name)}</td><td>${i.qty_on_hand}</td><td>${i.qty_reserved}</td><td><strong>${i.qty_available}</strong></td></tr>`).join('')||`<tr><td colspan="4" class="empty-state">No active items.</td></tr>`;applyLabels()};

function itemOptions(selected){return state.items.filter(i=>i.active||String(i.item_id)===String(selected)).map(i=>`<option value="${i.item_id}" ${String(i.item_id)===String(selected)?'selected':''}>${esc(i.item_name)}</option>`).join('')}
function addNewOrderRow(itemId){const i=state.items.find(x=>String(x.item_id)===String(itemId))||state.items.find(x=>x.active);if(!i)return;const tr=document.createElement('tr');const cached=state.availability?.find(x=>String(x.item_id)===String(i.item_id));const initialAvailable=cached?Number(cached.qty_available):Number(i.qty_on_hand||0);tr.innerHTML=`<td><select class="line-item">${itemOptions(i.item_id)}</select></td><td class="line-available" data-available="${initialAvailable}">${initialAvailable}</td><td><input class="line-qty" type="number" min="1" value="1"></td><td><input class="line-price" type="number" min="0" step=".01" value="${Number(i.unit_price).toFixed(2)}"></td><td class="line-amount">${money(i.unit_price)}</td><td><button type="button" class="text-btn line-remove">Remove</button></td>`;$('#orderItems tbody').appendChild(tr);wireLine(tr,false);refreshNewOrderAvailability().then(calcNewOrder);calcNewOrder()}
function wireLine(tr,edit,orderId=null){const sel=$('.line-item',tr),qty=$('.line-qty',tr),price=$('.line-price',tr);sel.onchange=async()=>{const i=state.items.find(x=>String(x.item_id)===sel.value);qty.value=1;if(i)price.value=Number(i.unit_price||0).toFixed(2);if(edit)await refreshEditAvailability(orderId);else await refreshNewOrderAvailability();edit?calcEditOrder():calcNewOrder()};qty.oninput=()=>{if(Number(qty.value)<1)qty.value=1;validateLine(tr);edit?calcEditOrder():calcNewOrder()};price.oninput=()=>edit?calcEditOrder():calcNewOrder();const remove=$('.line-remove',tr);remove.onclick=e=>{e.preventDefault();e.stopPropagation();tr.remove();edit?calcEditOrder():calcNewOrder()}}
function validateLine(tr){const a=Number($('.line-available',tr).dataset.available??Infinity),q=Number($('.line-qty',tr).value||0);tr.classList.toggle('inventory-warning',q>a);return q<=a}
function calcRows(root){let sum=0;$$('tbody tr',root).forEach(tr=>{const q=Number($('.line-qty',tr)?.value||0),p=Number($('.line-price',tr)?.value||0);sum+=q*p;const a=$('.line-amount',tr);if(a)a.textContent=money(q*p)});return sum}
function calcNewOrder(){const s=calcRows($('#orderItems'));$('#suggested').textContent=money(s);$('#total').textContent=money(s+Number($('#setup').value||0)+Number($('#deliveryFee').value||0)-Number($('#discount').value||0))}
$$('#setup,#deliveryFee,#discount').forEach(x=>x.oninput=calcNewOrder);$('#addItem').onclick=()=>addNewOrderRow();
async function refreshNewOrderAvailability(){const rows=$$('#orderItems tbody tr');const from=$('#orderDelivery').value,pickup=$('#orderPickup').value;if(!from||!pickup){rows.forEach(tr=>{const i=state.items.find(x=>String(x.item_id)===$('.line-item',tr).value),n=Number(i?.qty_on_hand||0);$('.line-available',tr).textContent=String(n);$('.line-available',tr).dataset.available=String(n);validateLine(tr)});return}const availability=await checkAvailability(from,pickup);state.availability=availability;const map=new Map(availability.map(x=>[String(x.item_id),Number(x.qty_available)]));rows.forEach(tr=>{const id=String($('.line-item',tr).value),i=state.items.find(x=>String(x.item_id)===id),n=map.has(id)?map.get(id):Number(i?.qty_on_hand||0);$('.line-available',tr).textContent=String(n);$('.line-available',tr).dataset.available=String(n);validateLine(tr)})}
$('#orderDelivery').onchange=refreshNewOrderAvailability;$('#orderPickup').addEventListener('change',refreshNewOrderAvailability);
function prefillCustomer(id){const c=state.customers.find(x=>String(x.customer_id)===String(id));if(c){$('#orderAddress').value=c.address||'';$('#orderCity').value=c.city||''}}
$('#orderCustomer').onchange=e=>prefillCustomer(e.target.value);
async function prepareNewOrder(customerId){if(!state.items.length)await loadItems();if(!state.customers.length)await loadCustomers();fillCustomerSelect(customerId);if(customerId)prefillCustomer(customerId);if(!$('#orderItems tbody').children.length)addNewOrderRow();await refreshNewOrderAvailability()}
async function saveNewOrder(status){const rows=$$('#orderItems tbody tr');if(!rows.length)return toast('Add at least one rental item.',true);if(rows.some(r=>!validateLine(r)))return toast('One or more quantities exceed available inventory.',true);const payload={customer_id:+$('#orderCustomer').value,event_date_time:new Date($('#orderEvent').value).toISOString(),event_address:$('#orderAddress').value.trim(),event_city:$('#orderCity').value.trim(),delivery_request_date_time:new Date($('#orderDelivery').value).toISOString(),pickup_request_date_time:new Date($('#orderPickup').value).toISOString(),setup_fee:+$('#setup').value||0,delivery_fee:+$('#deliveryFee').value||0,discount_amount:+$('#discount').value||0,order_status:status,notes:$('#orderNotes').value.trim()};const {data:o,error}=await db.from('orders').insert(payload).select('order_id,order_number').single();if(error)return toast(error.message,true);const lines=rows.map(r=>({order_id:o.order_id,item_id:+$('.line-item',r).value,quantity:+$('.line-qty',r).value,unit_price:+$('.line-price',r).value}));const {error:le}=await db.from('order_items').insert(lines);if(le){await db.from('orders').delete().eq('order_id',o.order_id);return toast(le.message,true)}toast(`${o.order_number} saved as ${status}.`);resetOrderForm();await Promise.all([loadDashboard(),loadReceivables()]);go('dashboard')}
$('#saveDraft').onclick=()=>saveNewOrder('Draft');$('#confirmOrder').onclick=()=>saveNewOrder('Confirmed');
function resetOrderForm(){$('#orderItems tbody').innerHTML='';$('#orderAddress').value='';$('#orderCity').value='';$('#setup').value=0;$('#deliveryFee').value=0;$('#discount').value=0;$('#orderNotes').value='';setDefaults();prepareNewOrder()}

async function loadReceivables(){const {data,error}=await db.from('vw_receivables').select('*').order('event_date_time',{ascending:false});if(error)return toast(error.message,true);state.receivables=data||[];renderReceivables()}
function renderReceivables(){const q=$('#receivableSearch').value.toLowerCase();const r=state.receivables.filter(x=>`${x.customer_name} ${x.phone} ${x.email} ${x.city}`.toLowerCase().includes(q));$('#receivableTable tbody').innerHTML=r.length?r.map(x=>`<tr><td>${fmt(x.event_date_time)}</td><td>${fmt(x.pickup_request_date_time)}</td><td><button class="text-btn order-open" data-id="${x.order_id}">${esc(x.order_number)}</button></td><td>${esc(x.customer_name)}</td><td>${esc(x.phone)}</td><td>${money(x.order_total)}</td><td>${money(x.amount_paid)}</td><td><strong class="danger">${money(x.amount_pending)}</strong></td><td><button class="secondary row-payment" data-id="${x.order_id}" data-customer="${x.customer_id}">Add Payment</button></td></tr>`).join(''):`<tr><td colspan="9" class="empty-state">No outstanding receivables.</td></tr>`;applyLabels()}
$('#receivableSearch').oninput=renderReceivables;$('#addPayment').onclick=()=>paymentManager();
async function paymentManager(customerId,orderId){let q=db.from('vw_order_financials').select('order_id,order_number,customer_id,customer_name,total_amount,amount_received,amount_pending').neq('order_status','Cancelled').order('event_date_time',{ascending:false});if(customerId)q=q.eq('customer_id',customerId);const {data,error}=await q;if(error)return toast(error.message,true);if(!data.length)return showModal('Payments','<p>No orders available.</p>');const selected=orderId||data[0].order_id;showModal('Add/Edit Payments',`<div class="payment-manager"><label>Order<select id="payOrderSelect">${data.map(o=>`<option value="${o.order_id}" ${String(o.order_id)===String(selected)?'selected':''}>${esc(o.order_number)} — ${esc(o.customer_name)}</option>`).join('')}</select></label><div id="paymentManagerBody"></div></div>`);$('#payOrderSelect').onchange=()=>renderPaymentOrder(+$('#payOrderSelect').value);renderPaymentOrder(+selected)}
async function renderPaymentOrder(orderId){const [{data:o,error},{data:pays}]=await Promise.all([db.from('vw_order_financials').select('*').eq('order_id',orderId).single(),db.from('payments').select('*').eq('order_id',orderId).order('payment_date_time',{ascending:false})]);if(error)return toast(error.message,true);$('#paymentManagerBody').innerHTML=`<div class="payment-summary"><div><span>Order Total</span><strong>${money(o.total_amount)}</strong></div><div><span>Paid</span><strong>${money(o.amount_received)}</strong></div><div><span>Balance</span><strong>${money(o.amount_pending)}</strong></div></div><div class="payment-head"><h3>Payment History</h3><button class="primary pay-new" data-id="${o.order_id}">+ Add Payment</button></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Method</th><th>Reference</th><th>Notes</th><th></th></tr></thead><tbody>${pays.length?pays.map(p=>`<tr><td>${fmt(p.payment_date_time)}</td><td>${esc(p.transaction_type)}</td><td>${money(p.amount)}</td><td>${esc(p.payment_method)}</td><td>${esc(p.reference_number)}</td><td>${esc(p.notes)}</td><td><button class="text-btn pay-edit" data-id="${p.payment_id}" data-order="${o.order_id}">Edit</button></td></tr>`).join(''):`<tr><td colspan="7">No payments yet.</td></tr>`}</tbody></table></div>`;applyLabels(mc)}
async function paymentForm(orderId,payment){const {data:o,error}=await db.from('vw_order_financials').select('*').eq('order_id',orderId).single();if(error)return toast(error.message,true);showModal(payment?'Edit Payment':'Add Payment',`<div class="payment-summary"><div><span>Order Total</span><strong>${money(o.total_amount)}</strong></div><div><span>Paid</span><strong>${money(o.amount_received)}</strong></div><div><span>Balance</span><strong>${money(o.amount_pending)}</strong></div></div><form id="paymentForm" class="modal-grid"><label>Type<select name="transaction_type"><option ${payment?.transaction_type==='Payment'?'selected':''}>Payment</option><option ${payment?.transaction_type==='Refund'?'selected':''}>Refund</option></select></label><label>Date / Time<input name="payment_date_time" type="datetime-local" value="${localInput(payment?.payment_date_time||new Date())}"></label><label>Amount<input name="amount" type="number" min=".01" step=".01" required value="${payment?.amount??''}"></label><label>Method<select name="payment_method">${['Zelle','Cash','Venmo','Credit Card','Check','Other'].map(x=>`<option ${payment?.payment_method===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Reference<input name="reference_number" value="${esc(payment?.reference_number)}"></label><label class="wide">Notes<input name="notes" value="${esc(payment?.notes)}"></label><div class="modal-actions wide"><button class="primary" type="submit">Save Payment</button></div></form>`);$('#paymentForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.order_id=orderId;v.amount=+v.amount;v.payment_date_time=new Date(v.payment_date_time).toISOString();if(v.transaction_type==='Payment'){const allowance=Number(o.amount_pending)+(payment?.transaction_type==='Payment'?Number(payment.amount):0);if(v.amount>allowance+.001)return toast(`Payment exceeds the available balance of ${money(allowance)}.`,true)}const q=payment?db.from('payments').update(v).eq('payment_id',payment.payment_id):db.from('payments').insert(v);const {error}=await q;if(error)return toast(error.message,true);modal.close();toast('Payment saved.');await Promise.all([loadReceivables(),loadDashboard(),loadCustomers()])}}

async function openOrder(orderId){const [{data:o,error},{data:lines},{data:pays}]=await Promise.all([db.from('vw_order_financials').select('*').eq('order_id',orderId).single(),db.from('order_items').select('order_item_id,item_id,quantity,unit_price,items(item_name)').eq('order_id',orderId),db.from('payments').select('*').eq('order_id',orderId).order('payment_date_time',{ascending:false})]);if(error)return toast(error.message,true);showModal(`Order ${o.order_number}`,`<div class="order-detail-head"><div><p><strong>${esc(o.customer_name)}</strong> · ${esc(o.order_status)} · ${esc(o.final_status)}</p></div><div class="order-detail-actions"><button class="primary order-edit-full" data-id="${o.order_id}">Edit Order</button><button class="secondary" onclick="window.print()">Print / Save PDF</button></div></div><div class="order-meta"><div><span>Phone</span><strong>${esc(o.phone)}</strong></div><div><span>Email</span><strong>${esc(o.email)}</strong></div><div><span>Event</span><strong>${fmt(o.event_date_time)}</strong></div><div><span>Delivery</span><strong>${fmt(o.delivery_request_date_time)}</strong></div><div><span>Pickup</span><strong>${fmt(o.pickup_request_date_time)}</strong></div><div><span>Balance</span><strong>${money(o.amount_pending)}</strong></div></div><h3>Packing List</h3><div class="table-wrap"><table><thead><tr><th>Item</th><th>Qty</th><th>Unit Price</th><th>Amount</th></tr></thead><tbody>${lines.map(x=>`<tr><td>${esc(x.items?.item_name)}</td><td><strong>${x.quantity}</strong></td><td>${money(x.unit_price)}</td><td>${money(x.quantity*x.unit_price)}</td></tr>`).join('')}</tbody></table></div><div class="order-summary"><div><span>Suggested Price</span><strong>${money(o.suggested_price)}</strong></div><div><span>Setup Fee</span><strong>${money(o.setup_fee)}</strong></div><div><span>Delivery Fee</span><strong>${money(o.delivery_fee)}</strong></div><div><span>Discount</span><strong>−${money(o.discount_amount)}</strong></div><div class="grand-total"><span>Total</span><strong>${money(o.total_amount)}</strong></div><div><span>Received</span><strong>${money(o.amount_received)}</strong></div><div><span>Pending</span><strong>${money(o.amount_pending)}</strong></div></div><h3>Payments</h3>${pays.length?pays.map(p=>`<p>${fmt(p.payment_date_time)} — ${esc(p.transaction_type)} ${money(p.amount)} (${esc(p.payment_method||'')})</p>`).join(''):'<p>No payments yet.</p>'}<div class="modal-actions"><button class="secondary order-add-payment" data-id="${o.order_id}" data-customer="${o.customer_id}">Manage Payments</button></div>`);applyLabels(mc)}

async function editOrder(orderId){const [{data:o,error},{data:lines}]=await Promise.all([db.from('orders').select('*').eq('order_id',orderId).single(),db.from('order_items').select('*').eq('order_id',orderId)]);if(error)return toast(error.message,true);showModal(`Edit ${o.order_number}`,`<form id="editOrderForm"><div class="order-edit-grid"><label>Event Date / Time<input id="editEvent" type="datetime-local" value="${localInput(o.event_date_time)}"></label><label>Status<select id="editStatus">${['Draft','Confirmed','Completed','Cancelled'].map(x=>`<option ${o.order_status===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Event Address<input id="editAddress" value="${esc(o.event_address)}"></label><label>Event City<input id="editCity" value="${esc(o.event_city)}"></label><label>Delivery Requested<input id="editDelivery" type="datetime-local" value="${localInput(o.delivery_request_date_time)}"></label><label>Pickup Requested<input id="editPickup" type="datetime-local" value="${localInput(o.pickup_request_date_time)}"></label><label class="wide">Notes<textarea id="editNotes">${esc(o.notes)}</textarea></label></div><h3>Rental Items</h3><div class="table-wrap"><table id="editItems"><thead><tr><th>Item</th><th>Available</th><th>Qty</th><th>Unit Price</th><th>Item Amount</th><th></th></tr></thead><tbody></tbody></table></div><button type="button" class="secondary" id="editAddItem">+ Add Item</button><div class="edit-order-pricing"><label>Suggested Price<strong id="editSuggested">$0.00</strong></label><label>Setup Fee<input id="editSetup" type="number" min="0" step=".01" value="${o.setup_fee}"></label><label>Delivery Fee<input id="editDeliveryFee" type="number" min="0" step=".01" value="${o.delivery_fee}"></label><label>Discount<input id="editDiscount" type="number" min="0" step=".01" value="${o.discount_amount}"></label><label class="total-row">Total<strong id="editTotal">$0.00</strong></label></div><div class="edit-order-footer"><span>Availability excludes this order's existing reservation.</span><button class="primary" type="submit">Save Order Changes</button></div></form>`,true);lines.forEach(l=>addEditRow(l,orderId));if(!lines.length)addEditRow({},orderId);await refreshEditAvailability(orderId);calcEditOrder();$('#editAddItem').onclick=async()=>{addEditRow({},orderId);await refreshEditAvailability(orderId);calcEditOrder()};['#editSetup','#editDeliveryFee','#editDiscount'].forEach(s=>$(s).oninput=calcEditOrder);$('#editDelivery').onchange=()=>refreshEditAvailability(orderId);$('#editPickup').onchange=()=>refreshEditAvailability(orderId);$('#editOrderForm').onsubmit=e=>saveEditOrder(e,orderId)}
function addEditRow(line={},orderId=null){const i=state.items.find(x=>String(x.item_id)===String(line.item_id))||state.items.find(x=>x.active);if(!i)return;const tr=document.createElement('tr');const cached=state.editAvailability?.find(x=>String(x.item_id)===String(i.item_id));const initialAvailable=cached?Number(cached.qty_available):Number(i.qty_on_hand||0);tr.innerHTML=`<td><select class="line-item">${itemOptions(i.item_id)}</select></td><td class="line-available" data-available="${initialAvailable}">${initialAvailable}</td><td><input class="line-qty" type="number" min="1" value="${line.quantity||1}"></td><td><input class="line-price" type="number" min="0" step=".01" value="${Number(line.unit_price??i.unit_price).toFixed(2)}"></td><td class="line-amount">$0.00</td><td><button type="button" class="text-btn line-remove">Remove</button></td>`;$('#editItems tbody').appendChild(tr);wireLine(tr,true,orderId);calcEditOrder()}
async function refreshEditAvailability(orderId){const from=$('#editDelivery').value,pickup=$('#editPickup').value;const availability=await checkAvailability(from,pickup,orderId);state.editAvailability=availability;const map=new Map(availability.map(x=>[String(x.item_id),Number(x.qty_available)]));$$('#editItems tbody tr').forEach(tr=>{const id=String($('.line-item',tr).value),i=state.items.find(x=>String(x.item_id)===id),n=map.has(id)?map.get(id):Number(i?.qty_on_hand||0);$('.line-available',tr).textContent=String(n);$('.line-available',tr).dataset.available=String(n);validateLine(tr)})}
function calcEditOrder(){const s=calcRows($('#editItems'));$('#editSuggested').textContent=money(s);$('#editTotal').textContent=money(s+Number($('#editSetup').value||0)+Number($('#editDeliveryFee').value||0)-Number($('#editDiscount').value||0))}
async function saveEditOrder(e,orderId){e.preventDefault();const rows=$$('#editItems tbody tr');if(!rows.length)return toast('Add at least one item.',true);if(rows.some(r=>!validateLine(r)))return toast('One or more quantities exceed available inventory.',true);const order={event_date_time:new Date($('#editEvent').value).toISOString(),event_address:$('#editAddress').value.trim(),event_city:$('#editCity').value.trim(),delivery_request_date_time:new Date($('#editDelivery').value).toISOString(),pickup_request_date_time:new Date($('#editPickup').value).toISOString(),setup_fee:+$('#editSetup').value||0,delivery_fee:+$('#editDeliveryFee').value||0,discount_amount:+$('#editDiscount').value||0,order_status:$('#editStatus').value,notes:$('#editNotes').value.trim()};const {error}=await db.from('orders').update(order).eq('order_id',orderId);if(error)return toast(error.message,true);const {error:de}=await db.from('order_items').delete().eq('order_id',orderId);if(de)return toast(de.message,true);const lines=rows.map(r=>({order_id:orderId,item_id:+$('.line-item',r).value,quantity:+$('.line-qty',r).value,unit_price:+$('.line-price',r).value}));const {error:ie}=await db.from('order_items').insert(lines);if(ie)return toast(ie.message,true);modal.close();toast('Order updated.');await Promise.all([loadDashboard(),loadReceivables()])}

async function loadAccounting(){if(!$('#accountingFrom').value)setDefaults();const from=$('#accountingFrom').value,to=$('#accountingTo').value;if(!from||!to)return;const [{data:s,error:se},{data:income,error:ie},{data:expenses,error:ee}]=await Promise.all([db.rpc('get_accounting_summary',{p_from_date:from,p_to_date:to}),db.from('vw_accounting_income').select('*').gte('income_date',from).lte('income_date',to).order('payment_date_time',{ascending:false}),db.from('expenses').select('*').gte('expense_date',from).lte('expense_date',to).order('expense_date',{ascending:false})]);if(se||ie||ee)return toast((se||ie||ee).message,true);const k=Array.isArray(s)?s[0]:s;$('#acctRevenue').textContent=money(k?.collected_revenue);$('#acctExpenses').textContent=money(k?.total_expenses);$('#acctNet').textContent=money(k?.net_cash);$('#acctOutstanding').textContent=money(k?.outstanding_balance);$('#incomeTable tbody').innerHTML=income.length?income.map(x=>`<tr><td>${fmtDate(x.income_date)}</td><td>${esc(x.customer_name)}</td><td><button class="text-btn order-open" data-id="${x.order_id}">${esc(x.order_number)}</button></td><td>${esc(x.items)}</td><td><strong>${money(x.revenue)}</strong></td></tr>`).join(''):`<tr><td colspan="5" class="empty-state">No income in this date range.</td></tr>`;$('#expenseTable tbody').innerHTML=expenses.length?expenses.map(x=>`<tr><td>${fmtDate(x.expense_date)}</td><td>${esc(x.description)}</td><td>${esc(x.category)}</td><td>${money(x.amount)}</td><td><button class="text-btn expense-edit" data-id="${x.expense_id}">Edit</button> <button class="text-btn expense-delete danger" data-id="${x.expense_id}">Delete</button></td></tr>`).join(''):`<tr><td colspan="5" class="empty-state">No expenses in this date range.</td></tr>`;applyLabels()}
$('#applyAccounting').onclick=loadAccounting;$('#addExpense').onclick=()=>expenseEditor();
function expenseEditor(x={}){showModal(x.expense_id?'Edit Expense':'Add Expense',`<form id="expenseForm" class="modal-grid"><label>Date<input name="expense_date" type="date" required value="${x.expense_date||dateInput(new Date())}"></label><label>Amount<input name="amount" type="number" min=".01" step=".01" required value="${x.amount??''}"></label><label class="wide">Description<input name="description" required value="${esc(x.description)}"></label><label>Category<select name="category">${['Equipment Purchase','Repair / Maintenance','Fuel / Delivery','Advertising','Supplies','Storage','Insurance','Website / Software','Other'].map(c=>`<option ${x.category===c?'selected':''}>${c}</option>`).join('')}</select></label><label class="wide">Notes<textarea name="notes">${esc(x.notes)}</textarea></label><div class="modal-actions wide"><button class="primary" type="submit">Save Expense</button></div></form>`);$('#expenseForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.amount=+v.amount;const q=x.expense_id?db.from('expenses').update(v).eq('expense_id',x.expense_id):db.from('expenses').insert(v);const {error}=await q;if(error)return toast(error.message,true);modal.close();toast('Expense saved.');await loadAccounting()}}

async function loadCategories(){const {data,error}=await db.from('partner_categories').select('*').order('display_order').order('category_name');if(error)return toast(error.message,true);state.categories=data||[]}
async function loadPartners(){await loadCategories();const {data,error}=await db.from('partners').select('*,partner_categories(category_name)').order('display_order').order('business_name');if(error)return toast(error.message,true);state.partners=data||[];renderPartners()}
function partnerLogo(p){if(p.logo_storage_path){const {data}=db.storage.from('partner-logos').getPublicUrl(p.logo_storage_path);return data.publicUrl}return p.logo_url||p.image_url||''}
function renderPartners(){const q=$('#partnerSearch').value.toLowerCase();const r=state.partners.filter(p=>`${p.business_name} ${p.partner_categories?.category_name||p.category} ${p.contact_name} ${p.service_areas}`.toLowerCase().includes(q));$('#partnersTable tbody').innerHTML=r.length?r.map(p=>`<tr><td>${partnerLogo(p)?`<img class="partner-logo-thumb" src="${esc(partnerLogo(p))}" alt="">`:'<span class="logo-placeholder">No logo</span>'}</td><td>${esc(p.business_name)}</td><td>${esc(p.partner_categories?.category_name||p.category)}</td><td>${esc(p.phone)}</td><td>${p.featured?'Yes':'No'}</td><td>${p.active?'Yes':'No'}</td><td>${p.display_order}</td><td class="partner-actions"><button class="text-btn partner-edit" data-id="${p.partner_id}">Edit</button></td></tr>`).join(''):`<tr><td colspan="8" class="empty-state">No partners yet.</td></tr>`;applyLabels()}
$('#partnerSearch').oninput=renderPartners;$('#newPartner').onclick=()=>partnerEditor();
function categoryOptions(selected){return state.categories.filter(c=>c.active||String(c.category_id)===String(selected)).map(c=>`<option value="${c.category_id}" ${String(c.category_id)===String(selected)?'selected':''}>${esc(c.category_name)}</option>`).join('')}
function partnerEditor(p={}){showModal(p.partner_id?'Edit Partner':'Add Partner',`<form id="partnerForm" class="modal-grid"><label>Business Name<input name="business_name" required value="${esc(p.business_name)}"></label><label>Category<div class="inline-field"><select name="category_id" required>${categoryOptions(p.category_id)}</select><button type="button" class="secondary" id="addCategory">+ New</button></div></label><label>Contact Name<input name="contact_name" value="${esc(p.contact_name)}"></label><label>Phone<input name="phone" value="${esc(p.phone)}"></label><label>Email<input name="email" type="email" value="${esc(p.email)}"></label><label>Website<input name="website_url" value="${esc(p.website_url)}"></label><label>Instagram<input name="instagram_url" value="${esc(p.instagram_url)}"></label><label>Facebook<input name="facebook_url" value="${esc(p.facebook_url)}"></label><label class="wide">Service Areas<input name="service_areas" value="${esc(p.service_areas)}"></label><label class="wide">Description<textarea name="description">${esc(p.description)}</textarea></label><label class="wide">Logo URL<input name="logo_url" placeholder="https://.../logo.png" value="${esc(p.logo_url)}"></label><label class="wide">Upload Logo<input name="logo_file" type="file" accept="image/*"><small>Uploaded logo takes priority over Logo URL.</small></label><label>Featured<select name="featured"><option value="false" ${!p.featured?'selected':''}>No</option><option value="true" ${p.featured?'selected':''}>Yes</option></select></label><label>Active<select name="active"><option value="true" ${p.active!==false?'selected':''}>Yes</option><option value="false" ${p.active===false?'selected':''}>No</option></select></label><label>Display Order<input name="display_order" type="number" min="0" value="${p.display_order??0}"></label><div class="modal-actions wide"><button class="primary" type="submit">Save Partner</button></div></form>`);$('#addCategory').onclick=()=>categoryEditor();$('#partnerForm').onsubmit=e=>savePartner(e,p)}
function categoryEditor(){showModal('Add Partner Category',`<form id="categoryForm" class="modal-grid"><label class="wide">Category Name<input name="category_name" required></label><div class="modal-actions wide"><button class="primary">Save Category</button></div></form>`);$('#categoryForm').onsubmit=async e=>{e.preventDefault();const name=new FormData(e.target).get('category_name').trim();const {error}=await db.from('partner_categories').insert({category_name:name,display_order:100});if(error)return toast(error.message,true);modal.close();toast('Category added.');await loadCategories()}}
async function savePartner(e,p){e.preventDefault();const fd=new FormData(e.target),file=fd.get('logo_file'),catId=+fd.get('category_id'),cat=state.categories.find(c=>c.category_id===catId);const v={business_name:fd.get('business_name').trim(),category_id:catId,category:cat?.category_name||'Other',contact_name:fd.get('contact_name'),phone:fd.get('phone'),email:fd.get('email'),website_url:fd.get('website_url'),instagram_url:fd.get('instagram_url'),facebook_url:fd.get('facebook_url'),service_areas:fd.get('service_areas'),description:fd.get('description'),logo_url:fd.get('logo_url'),featured:fd.get('featured')==='true',active:fd.get('active')==='true',display_order:+fd.get('display_order')||0};let partnerId=p.partner_id;if(partnerId){const {error}=await db.from('partners').update(v).eq('partner_id',partnerId);if(error)return toast(error.message,true)}else{const {data,error}=await db.from('partners').insert(v).select('partner_id').single();if(error)return toast(error.message,true);partnerId=data.partner_id}if(file&&file.size){const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase();const path=`${partnerId}/logo-${Date.now()}.${ext}`;const {error:ue}=await db.storage.from('partner-logos').upload(path,file,{upsert:true});if(ue)return toast(`Partner saved, but logo upload failed: ${ue.message}`,true);if(p.logo_storage_path)await db.storage.from('partner-logos').remove([p.logo_storage_path]);const {error:pe}=await db.from('partners').update({logo_storage_path:path}).eq('partner_id',partnerId);if(pe)return toast(pe.message,true)}modal.close();toast('Partner saved.');await loadPartners()}

// Delegated actions
document.addEventListener('click',async e=>{
 const ce=e.target.closest('.customer-edit');if(ce)return customerEditor(state.customers.find(c=>String(c.customer_id)===ce.dataset.id));
 const cn=e.target.closest('.customer-new-order');if(cn){go('neworder');return prepareNewOrder(cn.dataset.id)}
 const co=e.target.closest('.customer-orders');if(co){const {data,error}=await db.from('vw_order_financials').select('*').eq('customer_id',co.dataset.id).order('event_date_time',{ascending:false});if(error)return toast(error.message,true);showModal('Customer Orders',data.length?`<div class="table-wrap"><table><thead><tr><th>Event</th><th>Order</th><th>Total</th><th>Balance</th></tr></thead><tbody>${data.map(o=>`<tr><td>${fmt(o.event_date_time)}</td><td><button class="text-btn order-open" data-id="${o.order_id}">${esc(o.order_number)}</button></td><td>${money(o.total_amount)}</td><td>${money(o.amount_pending)}</td></tr>`).join('')}</tbody></table></div>`:'<p>No orders.</p>');applyLabels(mc);return}
 const cp=e.target.closest('.customer-payments');if(cp)return paymentManager(cp.dataset.id);
 const ie=e.target.closest('.item-edit');if(ie)return itemEditor(state.items.find(i=>String(i.item_id)===ie.dataset.id));
 const pe=e.target.closest('.partner-edit');if(pe)return partnerEditor(state.partners.find(p=>String(p.partner_id)===pe.dataset.id));
 const oo=e.target.closest('.order-open');if(oo)return openOrder(+oo.dataset.id);
 const oed=e.target.closest('.order-edit-full');if(oed)return editOrder(+oed.dataset.id);
 const op=e.target.closest('.order-add-payment,.row-payment');if(op){modal.close();return paymentManager(op.dataset.customer,op.dataset.id)}
 const pn=e.target.closest('.pay-new');if(pn)return paymentForm(+pn.dataset.id);
 const ped=e.target.closest('.pay-edit');if(ped){const {data,error}=await db.from('payments').select('*').eq('payment_id',ped.dataset.id).single();if(error)return toast(error.message,true);return paymentForm(+ped.dataset.order,data)}
 const xe=e.target.closest('.expense-edit');if(xe){const {data,error}=await db.from('expenses').select('*').eq('expense_id',xe.dataset.id).single();if(error)return toast(error.message,true);return expenseEditor(data)}
 const xd=e.target.closest('.expense-delete');if(xd){if(!confirm('Delete this expense?'))return;const {error}=await db.from('expenses').delete().eq('expense_id',xd.dataset.id);if(error)return toast(error.message,true);toast('Expense deleted.');return loadAccounting()}
 const f=e.target.closest('.fulfill');if(f){const now=new Date().toISOString(),update=f.dataset.type==='delivery'?{delivery_status:'Delivered',actual_delivery_date_time:now}:{pickup_status:'Picked Up',actual_pickup_date_time:now};const {error}=await db.from('orders').update(update).eq('order_id',f.dataset.id);if(error)return toast(error.message,true);toast(f.dataset.type==='delivery'?'Order marked delivered.':'Order marked picked up.');return loadDashboard()}
});
function applyLabels(root=document){root.querySelectorAll('table').forEach(t=>{const h=$$('thead th',t);t.querySelectorAll('tbody tr').forEach(r=>[...r.children].forEach((c,i)=>{if(c.tagName==='TD')c.dataset.label=h[i]?.textContent.trim()||''}))})}
boot();
})();
