const items=[{id:'ITEM-001',name:'White Resin Chair',desc:'White folding resin chair',qty:150,price:3},{id:'ITEM-002',name:"6' Rectangle Table",desc:'Lifetime 6-ft table',qty:25,price:12},{id:'ITEM-003',name:"6' Round Table",desc:'Round banquet table',qty:10,price:18},{id:'ITEM-004',name:'Cocktail Table',desc:'High-top cocktail table',qty:12,price:15},{id:'ITEM-005',name:'20×30 Tent',desc:'Commercial frame tent',qty:2,price:450}];
const pages=document.querySelectorAll('.page'),tabs=document.querySelectorAll('.navtab');function go(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));tabs.forEach(t=>t.classList.toggle('active',t.dataset.page===id));window.scrollTo(0,0)}tabs.forEach(t=>t.onclick=()=>go(t.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function renderItems(){itemsBody.innerHTML=items.map(x=>`<tr><td><strong>${x.name}</strong></td><td>${x.desc}</td><td>${x.qty}</td><td>$${x.price.toFixed(2)}</td><td>Yes</td><td><button class="text-btn">Edit</button></td></tr>`).join('')}renderItems();
const tbody=document.querySelector('#orderItems tbody');function addLine(item=items[0]){const tr=document.createElement('tr');tr.innerHTML=`<td><select class="itemSel">${items.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select></td><td class="avail">${item.qty}</td><td><input class="qty" type="number" min="1" value="1"></td><td><input class="price" type="number" min="0" step=".01" value="${item.price}"></td><td class="amount">$${item.price.toFixed(2)}</td><td><button class="text-btn remove">Remove</button></td>`;tbody.appendChild(tr);const sel=tr.querySelector('.itemSel'),qty=tr.querySelector('.qty'),price=tr.querySelector('.price');sel.value=item.id;function recalc(){const it=items.find(x=>x.id===sel.value);tr.querySelector('.avail').textContent=it.qty;tr.querySelector('.amount').textContent='$'+((+qty.value||0)*(+price.value||0)).toFixed(2);totals()}sel.onchange=()=>{const it=items.find(x=>x.id===sel.value);price.value=it.price;recalc()};qty.oninput=recalc;price.oninput=recalc;tr.querySelector('.remove').onclick=()=>{tr.remove();totals()};recalc()}
function totals(){let s=0;document.querySelectorAll('#orderItems .amount').forEach(a=>s+=+a.textContent.replace('$',''));suggested.textContent='$'+s.toFixed(2);let t=s+(+setup.value||0)+(+delivery.value||0)-(+discount.value||0);total.textContent='$'+t.toFixed(2);pending.textContent='$'+Math.max(0,t).toFixed(2)}[setup,delivery,discount].forEach(x=>x.oninput=totals);addItem.onclick=()=>addLine(items[Math.min(tbody.children.length,items.length-1)]);addLine(items[0]);addLine(items[1]);addLine(items[4]);
pickup.onchange=()=>{const d=new Date(pickup.value);d.setHours(d.getHours()+2);releaseTime.textContent=d.toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})};
customerSearch.oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#customerTable tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')};document.querySelectorAll('[data-action="neworder"]').forEach(b=>b.onclick=()=>go('orders'));
const modal=document.querySelector('#modal'),mc=document.querySelector('#modalContent');document.querySelector('.modal-close').onclick=()=>modal.close();function showModal(title,body){mc.innerHTML=`<h2>${title}</h2>${body}`;modal.showModal()}
addCustomer.onclick=()=>showModal('Add Customer',`<div class="modal-grid"><label>Name<input></label><label>Phone<input></label><label>City<input></label><label>Email<input type="email"></label><label class="wide">Address<input></label></div><div class="modal-actions"><button class="primary" onclick="modal.close()">Save Customer</button></div>`);newItem.onclick=()=>showModal('Add Item',`<div class="modal-grid"><label>Item Name<input></label><label>Total Qty<input type="number"></label><label class="wide">Description<input></label><label>Unit Price<input type="number" step=".01"></label><label>Active<select><option>Yes</option><option>No</option></select></label></div><div class="modal-actions"><button class="primary" onclick="modal.close()">Save Item</button></div>`);addPayment.onclick=()=>showModal('Add Payment',`<div class="modal-grid"><label>Order<select><option>SR-1025 — Raj Patel</option></select></label><label>Type<select><option>Payment</option><option>Refund</option></select></label><label>Date / Time<input type="datetime-local"></label><label>Amount<input type="number" step=".01"></label><label>Method<select><option>Zelle</option><option>Cash</option><option>Venmo</option><option>Credit Card</option><option>Check</option><option>Other</option></select></label><label>Reference<input></label><label class="wide">Notes<input></label></div><div class="modal-actions"><button class="primary" onclick="modal.close()">Save Payment</button></div>`);document.querySelectorAll('[data-action="history"]').forEach(b=>b.onclick=()=>showModal('Customer Order History',`<table><tr><th>Order</th><th>Event</th><th>Total</th><th>Balance</th></tr><tr><td><a class="order-link" href="?order=SR-1025" data-order-id="SR-1025">SR-1025</a></td><td>Sep 20</td><td>$1,200</td><td>$500</td></tr></table>`));

// Order detail / packing-sheet prototype. In the Firebase version this data will come from Orders, Order_Items and Payments.
const demoOrders={
 'SR-1025':{customer:'Raj Patel',phone:'469-555-1212',email:'raj@example.com',orderDate:'Sep 18, 2026',event:'Sep 20, 2026 · 5:00 PM',eventAddress:'456 Event Drive, McKinney, TX',delivery:'Sep 20, 2026 · 1:00 PM',pickup:'Sep 21, 2026 · 10:00 AM',release:'Sep 21, 2026 · 12:00 PM',status:'Confirmed',payment:'Open',items:[['White Resin Chair',60,3],['6\' Rectangle Table',8,12],['20×30 Tent',1,450]],setup:100,deliveryFee:75,discount:50,received:700,notes:'Call customer before delivery. Confirm tent placement on arrival.'},
 'SR-1026':{customer:'John Smith',phone:'214-555-1313',email:'john@example.com',orderDate:'Sep 18, 2026',event:'Sep 21, 2026 · 6:00 PM',eventAddress:'1200 Celebration Ln, Frisco, TX',delivery:'Sep 21, 2026 · 2:00 PM',pickup:'Sep 22, 2026 · 10:00 AM',release:'Sep 22, 2026 · 12:00 PM',status:'Confirmed',payment:'Settled',items:[['White Resin Chair',40,3],['Cocktail Table',4,15]],setup:50,deliveryFee:50,discount:0,received:280,notes:'Backyard delivery; use side gate.'},
 'SR-1027':{customer:'Amy Jones',phone:'972-555-1414',email:'amy@example.com',orderDate:'Sep 18, 2026',event:'Sep 22, 2026 · 4:00 PM',eventAddress:'88 Prosper Trail, Prosper, TX',delivery:'Sep 22, 2026 · 11:00 AM',pickup:'Sep 23, 2026 · 9:00 AM',release:'Sep 23, 2026 · 11:00 AM',status:'Confirmed',payment:'Settled',items:[['White Resin Chair',75,3],['6\' Round Table',8,18],['20×30 Tent',1,450]],setup:100,deliveryFee:75,discount:19,received:975,notes:'Tent and tables require setup.'}
};
function money(n){return '$'+Number(n||0).toFixed(2)}
function orderDetailHtml(id){
 const o=demoOrders[id]; if(!o)return '<p>Order details are not available in this prototype.</p>';
 const suggested=o.items.reduce((s,x)=>s+x[1]*x[2],0), total=suggested+o.setup+o.deliveryFee-o.discount, pending=Math.max(0,total-o.received);
 return `<div class="order-detail-head"><div><h2>Order ${id}</h2><p><strong>${o.customer}</strong> · ${o.status} · Payment ${o.payment}</p></div><div class="order-detail-actions"><button class="secondary" onclick="window.print()">Print / Save PDF</button></div></div>
 <div class="order-meta"><div><span>Customer</span><strong>${o.customer}</strong></div><div><span>Phone</span><strong>${o.phone}</strong></div><div><span>Email</span><strong>${o.email}</strong></div><div><span>Order Date</span><strong>${o.orderDate}</strong></div><div><span>Event Date / Time</span><strong>${o.event}</strong></div><div><span>Event Address</span><strong>${o.eventAddress}</strong></div><div><span>Delivery Requested</span><strong>${o.delivery}</strong></div><div><span>Pickup Requested</span><strong>${o.pickup}</strong></div><div><span>Inventory Available</span><strong>${o.release}</strong></div><div><span>Order Status</span><strong>${o.status}</strong></div></div>
 <h3 class="packing-title">Packing List</h3><div class="table-wrap"><table><thead><tr><th>Item</th><th>Qty to Pack</th><th>Unit Price</th><th>Amount</th></tr></thead><tbody>${o.items.map(x=>`<tr><td>${x[0]}</td><td><strong>${x[1]}</strong></td><td>${money(x[2])}</td><td>${money(x[1]*x[2])}</td></tr>`).join('')}</tbody></table></div>
 <div class="order-summary"><div><span>Suggested Price</span><strong>${money(suggested)}</strong></div><div><span>Setup Fee</span><strong>${money(o.setup)}</strong></div><div><span>Delivery Fee</span><strong>${money(o.deliveryFee)}</strong></div><div><span>Discount</span><strong>−${money(o.discount)}</strong></div><div class="grand-total"><span>Total Amount</span><strong>${money(total)}</strong></div><div><span>Amount Received</span><strong>${money(o.received)}</strong></div><div><span>Amount Pending</span><strong>${money(pending)}</strong></div></div>
 <div class="order-notes"><strong>Delivery / Packing Notes</strong><p>${o.notes||'—'}</p></div>`;
}
function openOrder(id, updateUrl=true){
  mc.innerHTML=orderDetailHtml(id);
  if(typeof modal.showModal === 'function') modal.showModal(); else modal.setAttribute('open','');
  if(updateUrl){const u=new URL(window.location.href);u.searchParams.set('order',id);history.pushState({order:id},'',u)}
}
document.addEventListener('click',e=>{
  const link=e.target.closest('a[data-order-id]');
  if(link){e.preventDefault();openOrder(link.dataset.orderId);}
});
modal.addEventListener('close',()=>{const u=new URL(window.location.href);if(u.searchParams.has('order')){u.searchParams.delete('order');history.replaceState({},'',u)}});
window.addEventListener('popstate',()=>{const id=new URL(window.location.href).searchParams.get('order');if(id)openOrder(id,false);else if(modal.open)modal.close()});
const initialOrder=new URL(window.location.href).searchParams.get('order');if(initialOrder)openOrder(initialOrder,false);
